### ISSUE TITLE
Add the ability to add expectations for a host

### ISSUE THREAD

**Issue by xel1045** [EpicScriptTime/update-wrapper#10]
To test before and after if the host is working. For example:

```
hosts:
  example.com:
    user: example
    sudo: true
    flavor: debian
    expectations:
      - type: HTTP_STATUS
        url: https://example
        status: 200
```

Reference: https://github.com/mtakaki/cachet-url-monitor#configuration
